# Generated by Django 4.0.2 on 2022-02-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Иванов Иван Иванович', max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=255)),
                ('desired_job', models.TextField()),
                ('desired_start', models.DateField()),
                ('desired_end', models.DateField()),
                ('languages', models.CharField(max_length=255)),
                ('volunteer_experience', models.TextField(null=True)),
                ('recommendations', models.TextField(null=True)),
                ('skills', models.TextField()),
                ('volunteer_book', models.CharField(max_length=255, null=True)),
                ('why', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('comments', models.TextField(null=True)),
            ],
        ),
    ]
