# Generated by Django 4.0.2 on 2022-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='volunteer_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='volunteer_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
