# Generated by Django 4.0.2 on 2022-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applications_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='fio',
            field=models.CharField(max_length=150),
        ),
    ]
